# Generated by Django 4.2.11 on 2024-04-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='static/myapp/img/default.jpg', upload_to='uploads', verbose_name='画像'),
        ),
    ]
